set_pump_speed:
  name: Set pump speed
  description: Set the run speed of a variable speed pump.
  target:
    entity:
      integration: omnilogic
      domain: switch
  fields:
    speed:
      name: Speed
      description: Speed for the VSP between min and max speed.
      required: true
      selector:
        number:
          min: 0
          max: 100000

set_v2_lights:
  name: Set V2 light effects
  description: Set the version 2 light effect speed or brightness
  target:
    entity:
      integration: omnilogic
      domain: light
  fields:
    speed:
      name: Speed
      description: Speed for the light effect (0-8) (Optional).
      required: false
      selector:
        number:
          min: 0
          max: 8
    brightness:
      name: Brightness
      description: Brightness for the light effect (0-4) (Optional).
      required: false
      selector:
        number:
          min: 0
          max: 4

set_chlor_timed_percent:
  name: Set chlorinator timed percent
  description: Set the timed percentage for a chlorinator.
  target:
    entity:
      integration: omnilogic
      domain: switch
  fields:
    timed_percent:
      name: Timed Percent
      description: Timed percentage for the chlorinator between 0 and 100.
      required: true
      selector:
        number:
          min: 0
          max: 100